# GoReleaser configuration
# https://goreleaser.com

version: 2

builds:
  - id: chatbotgate
    main: ./cmd/chatbotgate
    binary: chatbotgate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore arm64 on Windows (not commonly used)
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    builds:
      - chatbotgate
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - config.example.yaml
      - examples/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'typo'
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: ideamans
    name: chatbotgate
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## ChatbotGate {{ .Tag }}

    **Release Date**: {{ .Date }}

    ### Installation

    Download the appropriate binary for your platform below, or use Docker:

    ```bash
    docker pull ideamans/chatbotgate:{{ .Tag }}
    ```

  footer: |
    ### Verifying the Release

    You can verify the integrity of downloaded files using the checksums provided in `checksums.txt`.

    ```bash
    sha256sum -c checksums.txt
    ```

    **Full Changelog**: https://github.com/ideamans/chatbotgate/compare/{{ .PreviousTag }}...{{ .Tag }}
